from typing import Dict, Any, List
import logging
import re
import asyncio
from collections import Counter

# LLM manager for self-evaluation
from llm_providers.llm_manager import get_llm_response

logger = logging.getLogger("self_correction")

async def self_correct(query: str, initial_response: str, task_type: str = "general", max_iterations: int = 2) -> str:
    """
    Enhanced self-correction mechanism for LLM responses with iterative refinement.

    Args:
        query (str): The original user query.
        initial_response (str): The initial response generated by the LLM.
        task_type (str): The type of task (e.g., reasoning, summarization, insights).
        max_iterations (int): Maximum number of refinement iterations.

    Returns:
        str: The refined response.
    """
    try:
        current_response = initial_response
        iteration = 0
        
        while iteration < max_iterations:
            # Step 1: Evaluate the current response
            evaluation = await evaluate_response_enhanced(query, current_response, task_type)
            logger.info(f"Iteration {iteration + 1} - Evaluation results: {evaluation}")

            # Step 2: If response is acceptable, return it
            if evaluation["is_acceptable"]:
                logger.info(f"Response accepted after {iteration + 1} iteration(s)")
                return current_response

            # Step 3: Refine the response
            logger.info(f"Refining response (iteration {iteration + 1})...")
            refined_response = await refine_response_enhanced(query, current_response, evaluation, task_type)
            
            # Check if refinement actually improved the response
            if refined_response != current_response:
                current_response = refined_response
            else:
                logger.info("No improvement detected, stopping refinement")
                break
                
            iteration += 1

        return current_response

    except Exception as e:
        logger.error(f"Error in self-correction: {e}")
        return initial_response  # Fallback to the initial response

async def evaluate_response_enhanced(query: str, response: str, task_type: str) -> Dict[str, Any]:
    """
    Enhanced evaluation using LLM-based assessment and heuristic checks.

    Args:
        query (str): The original user query.
        response (str): The response to evaluate.
        task_type (str): The type of task.

    Returns:
        Dict[str, Any]: Evaluation results with detailed scoring.
    """
    issues = []
    scores = {}
    
    # 1. Basic heuristic checks
    heuristic_results = _perform_heuristic_checks(query, response, task_type)
    issues.extend(heuristic_results["issues"])
    scores.update(heuristic_results["scores"])
    
    # 2. LLM-based evaluation for more sophisticated assessment
    try:
        llm_evaluation = await _llm_based_evaluation(query, response, task_type)
        scores.update(llm_evaluation["scores"])
        issues.extend(llm_evaluation["issues"])
    except Exception as e:
        logger.warning(f"LLM evaluation failed, using heuristic only: {e}")
    
    # 3. Calculate overall acceptability
    overall_score = sum(scores.values()) / len(scores) if scores else 0.5
    is_acceptable = overall_score >= 0.7 and len(issues) <= 2
    
    return {
        "is_acceptable": is_acceptable,
        "overall_score": overall_score,
        "scores": scores,
        "issues": issues,
        "recommendations": _generate_improvement_recommendations(scores, issues)
    }

def _perform_heuristic_checks(query: str, response: str, task_type: str) -> Dict[str, Any]:
    """Perform rule-based heuristic checks."""
    issues = []
    scores = {}
    
    # Relevance check - keyword overlap
    query_words = set(re.findall(r'\b\w{3,}\b', query.lower()))
    response_words = set(re.findall(r'\b\w{3,}\b', response.lower()))
    relevance_score = len(query_words.intersection(response_words)) / len(query_words) if query_words else 1.0
    scores["relevance"] = min(relevance_score, 1.0)
    
    if relevance_score < 0.3:
        issues.append("Low relevance to query")
    
    # Completeness check
    word_count = len(response.split())
    min_words = {"reasoning": 50, "summarization": 30, "insights": 40, "general": 20}
    expected_min = min_words.get(task_type, 20)
    
    completeness_score = min(word_count / expected_min, 1.0)
    scores["completeness"] = completeness_score
    
    if word_count < expected_min:
        issues.append(f"Response too short for {task_type} task")
    
    # Clarity check - sentence structure and readability
    sentences = re.split(r'[.!?]+', response)
    avg_sentence_length = sum(len(s.split()) for s in sentences) / len(sentences) if sentences else 0
    clarity_score = 1.0 if 10 <= avg_sentence_length <= 25 else max(0.5, 1.0 - abs(avg_sentence_length - 17.5) / 17.5)
    scores["clarity"] = clarity_score
    
    if clarity_score < 0.6:
        issues.append("Clarity issues detected")
    
    # Coherence check - logical flow
    coherence_indicators = ["however", "therefore", "because", "since", "although", "furthermore", "moreover"]
    coherence_count = sum(1 for indicator in coherence_indicators if indicator in response.lower())
    coherence_score = min(coherence_count / 3, 1.0)
    scores["coherence"] = coherence_score
    
    if coherence_score < 0.3:
        issues.append("Poor logical flow")
    
    # Task-specific checks
    if task_type == "reasoning":
        reasoning_indicators = ["because", "therefore", "since", "due to", "as a result", "consequently"]
        reasoning_count = sum(1 for indicator in reasoning_indicators if indicator in response.lower())
        scores["reasoning_quality"] = min(reasoning_count / 2, 1.0)
        if reasoning_count == 0:
            issues.append("Lacks reasoning indicators")
    
    elif task_type == "summarization":
        # Check if summary captures key points
        summary_indicators = ["in summary", "overall", "in conclusion", "key points", "main"]
        summary_count = sum(1 for indicator in summary_indicators if indicator in response.lower())
        scores["summary_quality"] = min(summary_count / 1, 1.0)
        if summary_count == 0:
            issues.append("Lacks summarization structure")
    
    elif task_type == "explanation":
        # Check for explanation quality
        explanation_indicators = ["because", "means", "refers to", "in other words", "simply put"]
        explanation_count = sum(1 for indicator in explanation_indicators if indicator in response.lower())
        scores["explanation_quality"] = min(explanation_count / 2, 1.0)
        if explanation_count == 0:
            issues.append("Lacks explanation clarity indicators")

    elif task_type == "clarification":
        # Check for clarification quality
        clarification_indicators = ["additionally", "furthermore", "also", "more specifically", "in detail"]
        clarification_count = sum(1 for indicator in clarification_indicators if indicator in response.lower())
        scores["clarification_quality"] = min(clarification_count / 2, 1.0)
        if clarification_count == 0:
            issues.append("Lacks clarification expansion indicators")
    
    return {"issues": issues, "scores": scores}

async def _llm_based_evaluation(query: str, response: str, task_type: str) -> Dict[str, Any]:
    """Use LLM to evaluate response quality."""
    evaluation_prompt = f"""
    Please evaluate this response for quality on a scale of 0-1 for each criterion:

    Original Query: "{query}"
    Task Type: {task_type}
    Response: "{response}"

    Rate the following aspects (0.0 to 1.0):
    1. Relevance to query
    2. Accuracy of information
    3. Completeness of answer
    4. Clarity of expression
    5. Overall quality

    Also identify any specific issues. Respond in this exact format:
    RELEVANCE: [score]
    ACCURACY: [score]  
    COMPLETENESS: [score]
    CLARITY: [score]
    OVERALL: [score]
    ISSUES: [comma-separated list of issues, or "None"]
    """
    
    try:
        evaluation_response = await get_llm_response(evaluation_prompt)
        return _parse_llm_evaluation(evaluation_response)
    except Exception as e:
        logger.error(f"LLM evaluation failed: {e}")
        return {"scores": {}, "issues": []}

def _parse_llm_evaluation(evaluation_text: str) -> Dict[str, Any]:
    """Parse LLM evaluation response."""
    scores = {}
    issues = []
    
    lines = evaluation_text.split('\n')
    for line in lines:
        line = line.strip()
        if ':' in line:
            key, value = line.split(':', 1)
            key = key.strip().lower()
            value = value.strip()
            
            if key in ['relevance', 'accuracy', 'completeness', 'clarity', 'overall']:
                try:
                    scores[f"llm_{key}"] = float(value)
                except ValueError:
                    pass
            elif key == 'issues' and value.lower() != 'none':
                issues = [issue.strip() for issue in value.split(',')]
    
    return {"scores": scores, "issues": issues}

def _generate_improvement_recommendations(scores: Dict[str, float], issues: List[str]) -> List[str]:
    """Generate specific recommendations for improvement."""
    recommendations = []
    
    # Score-based recommendations
    for criterion, score in scores.items():
        if score < 0.5:
            if "relevance" in criterion:
                recommendations.append("Improve relevance by addressing the specific query more directly")
            elif "completeness" in criterion:
                recommendations.append("Provide more comprehensive coverage of the topic")
            elif "clarity" in criterion:
                recommendations.append("Improve clarity with better sentence structure and explanations")
            elif "coherence" in criterion:
                recommendations.append("Enhance logical flow with better transitions")
    
    # Issue-based recommendations
    for issue in issues:
        if "short" in issue.lower():
            recommendations.append("Expand the response with more detailed explanations")
        elif "relevance" in issue.lower():
            recommendations.append("Focus more specifically on the user's question")
        elif "clarity" in issue.lower():
            recommendations.append("Use simpler language and clearer explanations")
    
    return list(set(recommendations))  # Remove duplicates

async def refine_response_enhanced(query: str, response: str, evaluation: Dict[str, Any], task_type: str) -> str:
    """
    Enhanced response refinement using LLM-based improvements.

    Args:
        query (str): The original user query.
        response (str): The current response.
        evaluation (Dict[str, Any]): Evaluation results with issues and scores.
        task_type (str): The type of task.

    Returns:
        str: The refined response.
    """
    try:
        # Create refinement prompt based on evaluation
        refinement_prompt = _create_refinement_prompt(query, response, evaluation, task_type)
        
        # Get refined response from LLM
        refined_response = await get_llm_response(refinement_prompt)
        
        # Validate that refinement actually improved the response
        if len(refined_response.split()) < len(response.split()) * 0.8:
            logger.warning("Refinement resulted in significantly shorter response, keeping original")
            return response
            
        return refined_response
        
    except Exception as e:
        logger.error(f"Error in response refinement: {e}")
        # Fallback to rule-based refinement
        return _rule_based_refinement(response, evaluation["issues"])

def _create_refinement_prompt(query: str, response: str, evaluation: Dict[str, Any], task_type: str) -> str:
    """Create a prompt for LLM-based refinement."""
    issues = evaluation.get("issues", [])
    recommendations = evaluation.get("recommendations", [])
    scores = evaluation.get("scores", {})
    
    prompt = f"""
    Please improve the following response based on the identified issues and recommendations:

    Original Query: "{query}"
    Task Type: {task_type}
    Current Response: "{response}"

    Issues Identified:
    {chr(10).join(f"- {issue}" for issue in issues)}

    Recommendations for Improvement:
    {chr(10).join(f"- {rec}" for rec in recommendations)}

    Quality Scores (0-1 scale):
    {chr(10).join(f"- {criterion}: {score:.2f}" for criterion, score in scores.items())}

    Please provide an improved version that addresses these issues while maintaining the core message. 
    Make sure the improved response is:
    1. More relevant to the original query
    2. More complete and comprehensive
    3. Clearer and easier to understand
    4. Logically coherent and well-structured

    Improved Response:
    """
    
    return prompt

def _rule_based_refinement(response: str, issues: List[str]) -> str:
    """Fallback rule-based refinement when LLM refinement fails."""
    refined_response = response
    
    for issue in issues:
        if "too short" in issue.lower() or "completeness" in issue.lower():
            refined_response += "\n\nTo provide more comprehensive coverage, let me elaborate further on the key points mentioned above."
        
        elif "relevance" in issue.lower():
            refined_response = f"To directly address your question: {refined_response}"
        
        elif "clarity" in issue.lower():
            refined_response = refined_response.replace(". ", ". In other words, ")
        
        elif "reasoning" in issue.lower():
            refined_response += "\n\nThis conclusion is based on the analysis of the available information and logical reasoning."
        
        elif "flow" in issue.lower() or "coherence" in issue.lower():
            # Add transition words where appropriate
            refined_response = refined_response.replace(". ", ". Furthermore, ")
    
    return refined_response

# Legacy function for backward compatibility
def self_correct_sync(query: str, initial_response: str, task_type: str = "general") -> str:
    """Synchronous wrapper for the enhanced self-correction mechanism."""
    try:
        loop = asyncio.get_event_loop()
        return loop.run_until_complete(self_correct(query, initial_response, task_type))
    except RuntimeError:
        # If no event loop is running, create a new one
        return asyncio.run(self_correct(query, initial_response, task_type))