"""Added uploaded_at attribute to class Document

Revision ID: 2638aa2e6392
Revises: 6fbca63be52a
Create Date: 2025-07-20 12:24:58.314588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2638aa2e6392'
down_revision: Union[str, Sequence[str], None] = '6fbca63be52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column with a default value for existing rows
    op.add_column('document', sa.Column('uploaded_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # Remove the default value after the column is added
    op.alter_column('document', 'uploaded_at', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'uploaded_at')
    # ### end Alembic commands ###
