"""Modified insights attribute in class Message

Revision ID: 2d97310b74ae
Revises: 8649c3184015
Create Date: 2025-07-24 19:08:49.787093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d97310b74ae'
down_revision: Union[str, Sequence[str], None] = '8649c3184015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean invalid data in the 'insights' column
    op.execute(
        """
        UPDATE message
        SET insights = NULL
        WHERE insights IS NOT NULL AND NOT (insights::text ~ '^[{\\[].*[}\\]]$')
        """
    )
    # Alter the column type to JSON
    op.execute(
        "ALTER TABLE message ALTER COLUMN insights TYPE JSON USING insights::json"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'insights',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
