"""Added thumbs_up and thumbs_down attributes to table Message for self correction mechanism.)

Revision ID: 92d35b686a69
Revises: 91f9802245f2
Create Date: 2025-07-18 16:32:38.941231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d35b686a69'
down_revision: Union[str, Sequence[str], None] = '91f9802245f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thumbs_up', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('thumbs_down', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'thumbs_down')
    op.drop_column('message', 'thumbs_up')
    # ### end Alembic commands ###
