"""Added thumbs_up and thumbs_down attributes to table Message for self correction mechanism.

Revision ID: f4757f6af9da
Revises: 92d35b686a69
Create Date: 2025-07-18 16:33:55.504695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4757f6af9da'
down_revision: Union[str, Sequence[str], None] = '92d35b686a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thumbs_up', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('thumbs_down', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('response_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('response_pkey'))
    )
    # ### end Alembic commands ###
